cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from onlineshop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include('onlineshop.urls')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = pageNotFound

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from onlineshop.models import ShopList
from .cart import Cart
from .forms import CartAddProductForm
from onlineshop.models import Category

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(ShopList, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(ShopList, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    cats = Category.objects.all()
    return render(request, 'cart/detail.html', {'cart': cart, 'cats': cats, 'title': 'Корзина'})

cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1 style="text-align:center;">Ваша корзина</h1><br>
    <table class="cart" width="100%" border="solid" style="text-align:center;">
        <thead>
        <tr style="background-color:#3d6fa1;">
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ post.get_absolute_url }}">
                            <img src="
                                {% if product.photo %}
                                    {{ product.photo.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}" height="200" width="130">
                        </a>
                    </td>
                    <td>{{ product.title }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id%}">Remove</a></td>
                    <td class="num">₴{{ item.price }}</td>
                    <td class="num">₴{{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total" style="background-color:yellow;">
            <td><h4>Total</h4></td>
            <td colspan="4"></td>
            <td class="num" style="color:red;"><h4>₴{{ cart.get_total_price }}</h4></td>
        </tr>
        </tbody>
    </table>
<br>
    <p class="text-right">
        <a href="/shop/"><button type="button" class="btn btn-danger">Вернуться в магазин</button></a>
        <a href="{% url 'orders:order_create' %}"><button type="button" class="btn btn-success">Заказать</button></a>
    </p>
{% endblock %}