cart/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

onlineshop/urls.py
from django.urls import path
from .views import *
from cart.views import cart_detail

urlpatterns = [
    path('', index, name='home'),
    path('about/', about_us, name='about'),
    path('shop/', shop_page, name='shop'),
    path('addpage/', AddProduct.as_view(), name='addpage'),
    path('login/', LoginUser.as_view(), name='login'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', logout_user, name='logout'),
    path('user_room/', cart_detail, name='user_cart'),
    path('feedback/', ContactFormView.as_view(), name='contact_us'),
    path('search/', SearchProduct.as_view(), name='search_results'),
    path('shop/<slug:cat_slug>/', ShopCategory.as_view(), name='category'),
    path('category/<slug:post_slug>/', ShowPost.as_view(), name='post'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from onlineshop.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('', include('onlineshop.urls')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = pageNotFound

onlineshop/models.py
from django.db import models
from django.template.defaultfilters import slugify
# Create your models here.
from django.urls import reverse


class ShopList(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    stock = models.PositiveIntegerField()
    content = models.TextField(blank=True, verbose_name='Текст статьи')
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/", verbose_name='Фото')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    available = models.BooleanField(default=True, verbose_name='Доступен ли товар')
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    class Meta:
        verbose_name = 'Список товаров'
        verbose_name_plural = 'Список товаров'
        ordering = ['-time_create', 'title']


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=200, unique=True, db_index=True, verbose_name="URL")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['id']

onlineshop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.text import slugify

from .models import *


class AddPostForm(forms.ModelForm):
    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cat'].empty_label = 'Категория не выбрана'

    class Meta:
        model = ShopList
        fields = ['title', 'price', 'stock', 'content', 'photo', 'available', 'cat']
        widgets = {
            'title': forms.Textarea(attrs={'class': 'form-input', 'rows': 2}),
            'content': forms.Textarea(attrs={'cols': 60, 'rows': 10}),
            'price': forms.Textarea(attrs={'cols': 10, 'rows': 1}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 100:
            raise ValidationError('Длина превышает 100 символов')
        return title


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'rows': 3,
                                                                            'cols': 20, 'placeholder': 'Логин'}))
    email = forms.EmailField(label='Почта', widget=forms.EmailInput(attrs={'class': 'form-input', 'placeholder': 'myemail@gmail.com'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                                  'placeholder': 'Пароль'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                                         'placeholder': 'Повтор пароля'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input', 'rows': 3,
                                                                            'cols': 20, 'placeholder': 'Логин'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input', 'rows': 3,
                                                                                 'cols': 20, 'placeholder': 'Пароль'}))

onlineshop/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseNotFound
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, FormView, DetailView
from .forms import *
from .models import *
from cart.forms import CartAddProductForm
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

cats = Category.objects.all()


def index(request):
    return render(request, 'index.html', {'title': 'Главная страница', 'cats': cats})


def about_us(request):
    return render(request, 'about.html', {'title': 'О нас', 'cats': cats})


class ShopHome(ListView):
    paginate_by = 4
    model = ShopList
    template_name = 'shopping.html'
    posts = ShopList.objects.filter()

    def get_context_data(self, *, object_list=None, **kwargs):
        return {'cats': cats, 'title': 'Магазин', 'posts': self.posts}

    def get_queryset(self):
        return self.posts

def shop_page(request):
    # 'Новости'
    posts = ShopList.objects.all().order_by('-time_create')
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом,возвращаем первую страницу.
        page_obj = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее количество страниц,
        # возвращаем последнюю.
        page_obj = paginator.page(paginator.num_pages)
    return render(request, 'shopping.html',
                  {'page': page,
                   'cats': cats,
                   'title': 'Магазин',
                   'posts': page_obj, 'page_obj': page_obj})

class ShowPost(DetailView):
    model = ShopList
    template_name = 'show_post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        cart_product_form = CartAddProductForm()

        return {'cats': cats, 'title': 'Обьявление', 'product': self.get_object(),
                'cart_product_form': cart_product_form}


def pageNotFound(request, exception):
    return HttpResponseNotFound('<h1>Страница не найдена</h1>')


class AddProduct(LoginRequiredMixin, CreateView):
    model = ShopList
    template_name = 'addpage.html'
    form_class = AddPostForm
    success_url = reverse_lazy('shop')
    login_url = '/admin/'

    def get_context_data(self, **kwargs):
        return {'cats': cats, 'title': 'Добавить новый товар', 'form': self.form_class}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, **kwargs):
        return {'cats': cats, 'title': 'Регистрация', 'form': self.form_class}

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('home')


class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'login.html'

    def get_success_url(self):
        return reverse_lazy('shop')

    def get_context_data(self, **kwargs):
        return {'title': 'Авторизация', 'form': self.form_class, 'cats': cats}


def logout_user(request):
    logout(request)
    return redirect('login')


class ContactFormView(FormView):
    template_name = 'contact.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        print(form.cleaned_data)
        return redirect('home')

    def get_context_data(self, **kwargs):
        return {'title': 'Связаться с нами', 'form': self.form_class, 'cats': cats}


class ShopCategory(ListView):
    model = ShopList
    template_name = 'shopping.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        posts = ShopList.objects.filter(cat__slug=self.kwargs['cat_slug'], available=True).select_related('cat')
        return posts

    def get_context_data(self, *, object_list=None, **kwargs):
        posts = ShopList.objects.filter(cat__slug=self.kwargs['cat_slug'], available=True).select_related('cat')
        return {'title': 'Категория - ' + str(posts[0].cat), 'posts': posts, 'cats': cats, 'cat': posts[0].cat}


class SearchProduct(ListView):
    model = ShopList
    template_name = 'search_results.html'

    def get_queryset(self):  # новый
        query = self.request.GET.get('q')
        object_list = ShopList.objects.filter(
            Q(title__icontains=query) | Q(content__icontains=query) | Q(title__icontains=query.capitalize()))
        return object_list

    def get_context_data(self, *, object_list=None, **kwargs):
        return {'title': 'Результаты поиска: '+str(), 'posts': self.object_list, 'cats': cats}

onlineshop/templates/about.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>
<body>
{% block content %}
<div class="container" id="about">
<h1>Olex</h1><br><h2>- торговая площадка, которая гарантирует честность сделок между продавцом и покупцом.
    Компания была создана в 2014 году и предоставляет свои услуги в 3х странах мира!</h2></div>

<table>
    <tr><img src="{% static 'images/1.jpg' %}" width="33%" height="300px"></tr>
    <tr><img src="{% static 'images/2.jpg' %}" width="33%" height="300px"></tr>
    <tr><img src="{% static 'images/fotostok.jpg' %}" width="33%" height="300px"></tr>

</table>
{% endblock %}
</body>
</html>

onlineshop/templates/addpage.html
{% extends 'base.html' %}

{% block content %}

<form action="{% url 'addpage' %}" method='post' enctype="multipart/form-data" id="adding">
    {% csrf_token %}

    <div class="form-error">{{form.non_field_errors}}</div>

{% for f in form %}
    <p><h3><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label></h3>{{f}}
    <div class="form-error">{{f.errors}}</div>
{% endfor %}
<br>
    <button type="submit" class="btn btn-primary">Добавить</button>
</form>
{% endblock %}

onlineshop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
    <link type="text/css" href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/"><img src="{% static 'images/OLEX.png' %}" width="100px" height="50px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/shop/">Магазин <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about/">О нас</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="category/" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Категории
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for c in cats %}
          <a class="dropdown-item" href="{{c.get_absolute_url}}">{{c.name}}</a>
          {% endfor %}
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/shop/">Все категории</a>
        </div>
      </li>
        <li>
            <div class="d7">
<form action='/search/' method="get">
  <input name="q" type="text" placeholder="Искать здесь...">
  <button type="submit"></button>
</form>
</div>
        </li>
      <li>

        {% if request.user.is_authenticated %}
				<div class="but">
        <a href="/user_room/">

    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
      <button class="button blue" >
  <i class="fa fa-unlock"></i>
          Ваша корзина
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
  <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
</svg></button>
        {% else %}
      <button class="button blue" disabled>
          Корзина пуста
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
  <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
</svg>
        {% endif %}
    {% endwith %}
      </button>
        </a>

<a id="logout" class="button purple" href="/logout/">
  <span>Выйти </span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-right" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
  <path fill-rule="evenodd" d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
</svg>
</a>
      </div></li>
    </ul>
  </div>
				{% else %}
				<div class="but">
        <a id="login1" href="/login/">
      <button id="login" class="button blue">
  <i class="fa fa-unlock"></i>
  <span>Войти </span>
      </button>
        </a>

<a id="register" class="button purple" href="/register/">
  <i class="fa fa-user-plus"></i>
  <span>Зарегистрироваться </span>
</a>
      </div></li>
    </ul>
  </div>
				{% endif %}

</nav>



<!-- Блок контента -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!-- Конец блока контента -->
</body>

<!-- Footer -->

<footer id="footer" class="footer-1">
<div class="main-footer widgets-dark typo-light">
<div class="container">
<div class="row">

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget subscribe no-box">
<h5 class="widget-title">OLEX<span></span></h5>
<p>About the company, little discription will goes here.. </p>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Quick Links<span></span></h5>
<ul class="thumbnail-widget">
<li>
<div class="thumb-content"><a href="#.">Get Started</a></div>
</li>
<li>
<div class="thumb-content"><a href="#.">Top Leaders</a></div>
</li>
<li>
<div class="thumb-content"><a href="/about/">Success Story</a></div>
</li>
<li>
<div class="thumb-content"><a href="#.">Event/Tickets</a></div>
</li>
<li>
<div class="thumb-content"><a href="#.">News</a></div>
</li>
<li>
<div class="thumb-content"><a href="#.">Lifestyle</a></div>
</li>
<li>
<div class="thumb-content"><a href="/about/">About</a></div>
</li>
</ul>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">
<div class="widget no-box">
<h5 class="widget-title">Get Started<span></span></h5>
<p>Get access to your full Training and Marketing Suite.</p>
<a class="btn" href="/register/" target="_blank">Register Now</a>
</div>
</div>

<div class="col-xs-12 col-sm-6 col-md-3">

<div class="widget no-box">
<h5 class="widget-title">Contact Us<span></span></h5>
<p><a href="mailto:olegtar25@gmail.com" title="glorythemes">olegtar25@gmail.com</a></p>
<p><a href="/feedback/"><button type="button" class="btn btn-info" id="contact_us">Связаться с нами</button></a></p>

<ul class="social-footer2">
<li class=""><a title="Youtube" target="_blank" href="//youtube.com"><img alt="youtube" width="30" height="30" src="https://www.youtube.com/img/desktop/yt_1200.png"></a></li>
<li class=""><a href="//facebook.com" target="_blank" title="Facebook"><img alt="Facebook" width="30" height="30" src="https://www.facebook.com/images/fb_icon_325x325.png"></a></li>
<li class=""><a href="//twitter.com" target="_blank" title="Twitter"><img alt="Twitter" width="30" height="30" src="https://help.twitter.com/content/dam/help-twitter/brand/logo.png"></a></li>
<li class=""><a title="instagram" target="_blank" href="//instagram.com"><img alt="instagram" width="30" height="30" src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Instagram_logo_2022.svg/800px-Instagram_logo_2022.svg.png"></a></li>
</ul>
</div>
</div>

</div>
</div>
</div>

<div class="footer-copyright">
<div class="container">
<div class="row">
<div class="col-md-12 text-center">
<p>Copyright OLEX Company © 2022. All rights reserved.</p>
</div>
</div>
</div>
</div>
</footer>
<!-- Конец footer'а и страницы -->

</body>
</html>

onlineshop/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<img src="{% static 'images/3.png' %}" width="100%" height="750px">

{% endblock %}

onlineshop/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}



<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/style.css" media="screen" type="text/css" />
	<link rel="icon" href="http://vladmaxi.net/favicon.ico" type="image/x-icon">
	<link rel="shortcut icon" href="http://vladmaxi.net/favicon.ico" type="image/x-icon">
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body id="login-back">
<div id="login-form">
    <h1>Авторизация на сайте</h1>

        <fieldset>
            <form method="post">
                {% csrf_token %}
                {% for f in form %}
                <h4><p><label class="form-label">{{f.label}}: </label></p></h4>{{ f }}
                    <div class="form-error">{{ f.errors }}</div><br>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Войти</button>
                <footer class="clearfix">
                        <p><a href="/register/">Забыли пароль?</a></p>
                </footer>
            </form>
        </fieldset>

    </div>
</body>
</html>

{% endblock %}

onlineshop/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}



<html>
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="css/style.css" media="screen" type="text/css" />
	<link rel="icon" href="http://vladmaxi.net/favicon.ico" type="image/x-icon">
	<link rel="shortcut icon" href="http://vladmaxi.net/favicon.ico" type="image/x-icon">
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
</head>
<body id="login-back">
<div id="login-form">
    <h1>Регистрация на сайте</h1>

        <fieldset>
            <form method="post">
                {% csrf_token %}
                {% for f in form %}
                <h4><p><label class="form-label">{{f.label}}: </label></p></h4>{{ f }}
                    <div class="form-error">{{ f.errors }}</div><br>
                {% endfor %}

                <button type="submit" class="btn btn-primary">Регистрация</button>

            </form>
        </fieldset>

    </div>
</body>
</html>

{% endblock %}

onlineshop/templates/search_results.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

   <div id="main" class="product-list">
        <h1 id="main-text">{% if cat %}{{ cat.name }}{% else %}Products{% endif %}</h1> <br>
        {% for product in posts %}
            <div class="item">
                <div class="article-panel">
	                <p class="first">Категория: {{product.cat}}<br> Дата: {{product.time_update|date:"d-m-Y H:i:s"}}</p>

			</div>
                <a href="{{ product.get_absolute_url }}" style="color:black;">
                    <img src="{% if product.photo %}{{ product.photo.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}" width="240" height="300" id="img-prod">

                    <h6>{{ product.title }}</h6>
                    {% autoescape on %} {{product.content|linebreaks|truncatewords:5}} {% endautoescape %}
                    <h5><p class="price" style="color:red;">₴{{ product.price }}</p></h5>
                </a>
            </div>
        {% endfor %}
    </div>
<img src="{% static 'images/dno_magaz.png' %}" width="100%" height="20px">
<div class="container ending"><h5>К сожалению, это все товары что мы можем вам предложить на данный момент...</h5></div>
{% endblock %}

onlineshop/templates/show_post.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    {% if cat %}{{ cat.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.photo %}{{ product.photo.url }}{% else %}{% static 'images/no_image.png' %}{% endif %}" width="400" id="post_img">
        <h1>{{ product.title }}</h1>
        <h3><a href="{{ product.cat.get_absolute_url }}" style="color:black;">{{ product.cat }}</a></h3>
        <h3><p class="price" style="color:red;">₴{{ product.price }}</p></h3>
        {{ product.content|linebreaks }}
    </div>

<form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success">Добавить в корзину</button>
</form>

<img src="{% static 'images/dno_magaz.png' %}" width="100%" height="100px">
{% endblock %}

onlineshop/templates/user_room.html
{% extends 'base.html' %}
{% block content %}
<a class="nav-link" href="{% url 'cart:cart_detail' %}" >
    {% with total_items=cart|length %}
        {% if cart|length > 0 %}
            Ваша корзина:
                {{ total_items }} товар{{ total_items|pluralize }},
                ${{ cart.get_total_price }}
        {% else %}
            Ваша корзина пуста.
        {% endif %}
          {% endwith %}</a>

{% endblock %}